src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @Assert\Regex(pattern="/^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$/u", message="Entrer un nom valide.") 
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @Assert\Regex(pattern="/^[a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]+$/u", message="Entrer un prénom valide.") 
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @Assert\Regex(pattern="/^(?:0[1-9]|[1-8]\d|9[0-8])\d{3}$/", message="Entrer un code postal valide.") 
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cp;

    /**
     * @Assert\Length(min = 10, max = 13, minMessage = "Un numéro de télephone comporte un minimum 10 caractère.", maxMessage = "Un numéro de télephone comporte un maximum 13 caractère.")
     * @Assert\Regex(pattern="/^((\+|00)33\s?|0)[67](\s?\d{2}){4}$/", message="Entrer un numéro de télephone valide.") 
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_delete;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_date_login;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_date_logout;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateDelete(): ?\DateTimeInterface
    {
        return $this->date_delete;
    }

    public function setDateDelete(?\DateTimeInterface $date_delete): self
    {
        $this->date_delete = $date_delete;

        return $this;
    }

    public function getLastDateLogin(): ?\DateTimeInterface
    {
        return $this->last_date_login;
    }

    public function setLastDateLogin(?\DateTimeInterface $last_date_login): self
    {
        $this->last_date_login = $last_date_login;

        return $this;
    }

    public function getLastDateLogout(): ?\DateTimeInterface
    {
        return $this->last_date_logout;
    }

    public function setLastDateLogout(?\DateTimeInterface $last_date_logout): self
    {
        $this->last_date_logout = $last_date_logout;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class,[
                'required'=> true,
                'constraints' => [
                    new NotBlank(["message" => "Entrer un nom valide"]),
                ]
            ],
            )
            ->add('prenom',TextType::class,[
                'required'=> true,
                'label'=>'Prénom',
                'constraints' => [
                    new NotBlank(["message" => "Entrer un nom valide"]),
                ]
            ],
            )
            ->add('email',EmailType::class,[
                'required'=> true,
                'constraints' => [
                new NotBlank(["message" => "Entrer un email valide"]),
                ]
            ],
            )
            ->add('telephone',TelType::class,[
                'required'=> true,
                'label'=>'Téléphone',
                'constraints' => [
                new NotBlank(["message" => "Entrer un numéro de télephone valide"]),
                ]
            ],
            )
            //->add('roles')
            ->add('password', RepeatedType::class,[
                'type' => PasswordType::class,
                'required'=> true,
                'label'=> 'Mot de passe',
                'first_options'  => ['label' => 'Mot de passe'],
                'second_options' => ['label' => 'Confirmation du mot de passe'],
                
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Doctrine\ORM\EntityManagerInterface;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/index', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository,UserPasswordHasherInterface $encoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //met tout en 0 et pas en +33
            $user->setTelephone(str_replace("+33","0",$user->getTelephone()));
            //hash le mot de passe
            $hash = $encoder->hashPassword($user , $user->getPassword());
            $user->setPassword($hash);
            //ajoute un role à l'utilisateur
            $user->setRoles(['ROLE_USER']);
            if($userRepository->findOneBy(['telephone'=>$user->getTelephone()])){
                $this->addFlash('error', 'Ce numéro de télephone est déja associé à un compte.');
            }
            else{
                $userRepository->add($user, true);
                // envoie un message de succes
                $this->addFlash('success', 'Un mail vous à été envoyer, afin de procéder à une verification de votre compte.');
            }
            
            
        }
        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository,UserPasswordHasherInterface $encoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->hashPassword($user , $user->getPassword());
            $user ->setPassword($hash);
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManage): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $user->setDateDelete(new \DateTime('@'.strtotime('now')));
            $entityManager->persist($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/login', name: 'app_user_login', methods: [])]
    public function editLastDateLogin(User $user, EntityManagerInterface $entityManager): Response
    {
        $user->setLastDateLogin(new \DateTime());
        $entityManager->persist( $user);
        $entityManager->flush();
        return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/thsi/logout', name: 'app_user_logout', methods: ['GET'])]
    public function editLastDateLogout(User $user, EntityManagerInterface $entityManager): Response
    {
        dd('logout');
    }
    
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-md">
            {{ form_label(form.nom) }}
            {{ form_widget(form.nom) }}
            <span class="error"> {{ form_errors(form.nom) }} </span>
        </div>
        <div class="col-md">
            {{ form_label(form.prenom) }}
            {{ form_widget(form.prenom) }}
            <span class="error"> {{ form_errors(form.prenom) }} </span>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            {{ form_label(form.email) }}
            {{ form_widget(form.email) }}
            <span class="error"> {{ form_errors(form.email) }} </span>
        </div>
        <div class="col-md">
            {{ form_label(form.telephone) }}
            {{ form_widget(form.telephone) }}
            <span class="error"> {{ form_errors(form.telephone) }} </span>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ form_widget(form.password) }}
            <span class="error">  {{ form_errors(form.password) }} </span>
        </div>
    </div>
    <div class="d-grid gap-2 col-6 mx-auto mt-4">
        <button class="btn btn-send mt-4 mb-4" type="submit"> {{ button_label|default('Enregistrer') }}</button>
    </div>
   
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de tout les utilisateurs{% endblock %}

{% block body %}
    <h2>Liste de tout les utilisateurs</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Email</th>
                <th>Téléphone</th>
                <th>Adresse</th>
                <th>Code Postal</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Delete</th>
                <th>Last login</th>
                <th>Last logout</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.telephone }}</td>
                <td>{{ user.adresse }}</td>
                <td>{{ user.cp }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.dateDelete is empty ? ""  : user.dateDelete|date('d M Y H:i')|format_datetime('medium','short',locale='fr')}}</td>
                <td>{{ user.lastDateLogin is empty ? ""  : user.lastDateLogin|date('d M Y H:i')|format_datetime('medium','short',locale='fr') }}</td>
                <td>{{ user.lastDateLogout is empty ? ""  : user.lastDateLogout|date('d M Y H:i')|format_datetime('medium','short',locale='fr') }}</td>

                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
<div class="container-fluid inscription">
    <div class="card card-inscription position-absolute top-50 start-50 translate-middle shadow-lg p-5 mb-8 rounded">
        <h2>Inscrivez-vous</h2>
        <!--Sucess Message -->
        {% for message in app.flashes('success')%}
            <div class="alert alert-success center" role="alert" id="sucess">
                <span>{{message}}<span>
            </div>
        {% endfor %}
         <!--Error Message -->
        {% for message in app.flashes('error')%}
            <div class="alert alert-danger center" role="alert" id="sucess">
                <span>{{message}}<span>
            </div>
        {% endfor %}
        {{ include('user/_form.html.twig') }}
        <p> Vous avez déja un compte <a href="{{ path('app_login') }}"> connectez-vous </a> </p>
    </div>
</div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}